import type { ImportDiscoveryState } from "./types";

export const SEED_IMPORT_DISCOVERY: ImportDiscoveryState = {
  scanComplete: true,
  games: [
    {
      id: "disc-1",
      title: "Armalyte",
      publisher: "Thalamus",
      year: 1988,
      roms: ["armalyte.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-2",
      title: "Bubble Bobble",
      publisher: "Firebird",
      year: 1987,
      roms: ["bubble-bobble.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-3",
      title: "Commando",
      publisher: "Elite Systems",
      year: 1985,
      roms: ["commando.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-4",
      title: "Great Giana Sisters",
      publisher: "Rainbow Arts",
      year: 1987,
      roms: ["giana-sisters.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-5",
      title: "The Last Ninja",
      publisher: "System 3",
      year: 1987,
      roms: ["last-ninja-1.d64", "last-ninja-2.d64", "last-ninja-3.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-6",
      title: "Montezuma's Revenge",
      publisher: "Parker Brothers",
      year: 1984,
      roms: ["montezumas-revenge.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-7",
      title: "Turrican",
      publisher: "Rainbow Arts",
      year: 1990,
      roms: ["turrican.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-8",
      title: "Wizball",
      publisher: "Ocean",
      year: 1987,
      roms: ["wizball.d64"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-9",
      title: null,
      publisher: null,
      year: null,
      roms: ["game-tape2-1.tap", "game-tape2-2.tap"],
      alreadyImported: false,
      selected: true,
    },
    {
      id: "disc-10",
      title: "Ghosts 'n Goblins",
      publisher: "Elite Systems",
      year: 1986,
      roms: ["ghosts-n-goblins.d64"],
      alreadyImported: true,
      selected: false,
    },
    {
      id: "disc-11",
      title: "Impossible Mission",
      publisher: "Epyx",
      year: 1984,
      roms: ["impossible-mission.d64"],
      alreadyImported: true,
      selected: false,
    },
    {
      id: "disc-12",
      title: "International Soccer",
      publisher: "Commodore",
      year: 1983,
      roms: ["international-soccer.d64"],
      alreadyImported: true,
      selected: false,
    },
    {
      id: "disc-13",
      title: "Jet Set Willy",
      publisher: "Software Projects",
      year: 1984,
      roms: ["jet-set-willy.d64"],
      alreadyImported: true,
      selected: false,
    },
    {
      id: "disc-14",
      title: "Paradroid",
      publisher: "Hewson",
      year: 1985,
      roms: ["paradroid.d64"],
      alreadyImported: true,
      selected: false,
    },
  ],
};
