import type { CarouselState } from "./types";

export const SEED_CAROUSEL: CarouselState = {
	activeCompilationId: "compilation-all-games",
	compilationPositions: {},
	games: [
		{
			id: "game-bubble",
			title: "Bubble Bobble",
			sortTitle: "Bubble Bobble",
			publisher: "Taito",
			year: 1987,
			coverUrl: "https://placehold.co/160x200/1a1a2e/4040ff?text=Bubble+Bobble",
			launchable: true,
			hasRom: true,
			hasQuickstart: true,
			hasSave: true,
		},
		{
			id: "game-elite",
			title: "Elite",
			sortTitle: "Elite",
			publisher: "Firebird",
			year: 1985,
			coverUrl: "https://placehold.co/160x200/1a1a2e/4040ff?text=Elite",
			launchable: true,
			hasRom: true,
			hasQuickstart: false,
			hasSave: true,
		},
		{
			id: "game-iridis",
			title: "Iridis Alpha",
			sortTitle: "Iridis Alpha",
			publisher: "Hewson Consultants",
			year: 1986,
			coverUrl: "https://placehold.co/160x200/1a1a2e/4040ff?text=Iridis+Alpha",
			launchable: true,
			hasRom: true,
			hasQuickstart: true,
			hasSave: false,
		},
		{
			id: "game-monty",
			title: "Monty on the Run",
			sortTitle: "Monty on the Run",
			publisher: "Gremlin Graphics",
			year: 1985,
			coverUrl:
				"https://placehold.co/160x200/1a1a2e/4040ff?text=Monty+on+the+Run",
			launchable: true,
			hasRom: true,
			hasQuickstart: true,
			hasSave: true,
		},
		{
			id: "game-outrun",
			title: "Outrun",
			sortTitle: "Outrun",
			publisher: "U.S. Gold",
			year: 1988,
			launchable: false,
			blockingReason: "No ROM configured",
			hasRom: false,
			hasQuickstart: false,
			hasSave: false,
		},
		{
			id: "game-summer",
			title: "Summer Games II",
			sortTitle: "Summer Games II",
			publisher: "Epyx",
			year: 1985,
			coverUrl:
				"https://placehold.co/160x200/1a1a2e/4040ff?text=Summer+Games+II",
			launchable: true,
			hasRom: true,
			hasQuickstart: false,
			hasSave: false,
		},
		{
			id: "game-zzap",
			title: "Zzap!64 Megatape 1",
			sortTitle: "Zzap!64 Megatape 1",
			publisher: "Newsfield Publications",
			year: 1986,
			coverUrl:
				"https://placehold.co/160x200/1a1a2e/4040ff?text=Zzap!64+Megatape+1",
			launchable: true,
			hasRom: true,
			hasQuickstart: false,
			hasSave: false,
		},
	],
};
