import type { ControlsState } from "./types";

export const SEED_CONTROLS: ControlsState = {
	owners: [
		{
			id: "family-logitech",
			name: "Logitech",
			type: "family",
		},
		{
			id: "family-xbox",
			name: "Microsoft Xbox",
			type: "family",
		},
		{
			id: "family-dualshock",
			name: "Sony DualShock",
			type: "family",
		},
		{
			id: "controller-logitech-dual-action",
			name: "Logitech Dual Action",
			type: "controller",
			familyId: "family-logitech",
			familyName: "Logitech",
		},
		{
			id: "controller-dualshock-4",
			name: "DualShock 4",
			type: "controller",
			familyId: "family-dualshock",
			familyName: "Sony DualShock",
		},
		{
			id: "controller-xbox-360",
			name: "Xbox 360 Controller",
			type: "controller",
			familyId: "family-xbox",
			familyName: "Microsoft Xbox",
		},
		{
			id: "controller-dualsense",
			name: "DualSense",
			type: "controller",
			familyId: undefined,
			familyName: undefined,
		},
	],
	controls: [
		// Logitech family controls
		{
			id: "ctrl-logitech-1",
			ownerId: "family-logitech",
			controlName: "A",
			canonicalName: "button_south",
			event: "button_1",
		},
		{
			id: "ctrl-logitech-2",
			ownerId: "family-logitech",
			controlName: "B",
			canonicalName: "button_east",
			event: "button_2",
		},
		{
			id: "ctrl-logitech-3",
			ownerId: "family-logitech",
			controlName: "X",
			canonicalName: "button_west",
			event: "button_0",
		},
		{
			id: "ctrl-logitech-4",
			ownerId: "family-logitech",
			controlName: "Y",
			canonicalName: "button_north",
			event: "button_3",
		},
		{
			id: "ctrl-logitech-6",
			ownerId: "family-logitech",
			controlName: "D-Down",
			canonicalName: "dpad_down",
			event: "button_14",
		},
		{
			id: "ctrl-logitech-7",
			ownerId: "family-logitech",
			controlName: "D-Left",
			canonicalName: "dpad_left",
			event: "button_15",
		},
		{
			id: "ctrl-logitech-8",
			ownerId: "family-logitech",
			controlName: "D-Right",
			canonicalName: "dpad_right",
			event: "button_13",
		},
		{
			id: "ctrl-logitech-9",
			ownerId: "family-logitech",
			controlName: "L1",
			canonicalName: "left_shoulder",
			event: "button_4",
		},
		{
			id: "ctrl-logitech-10",
			ownerId: "family-logitech",
			controlName: "R1",
			canonicalName: "right_shoulder",
			event: "button_5",
		},
		{
			id: "ctrl-logitech-11",
			ownerId: "family-logitech",
			controlName: "L2",
			canonicalName: "left_trigger",
			event: "button_6",
		},
		{
			id: "ctrl-logitech-12",
			ownerId: "family-logitech",
			controlName: "R2",
			canonicalName: "right_trigger",
			event: "button_7",
		},
		{
			id: "ctrl-logitech-13",
			ownerId: "family-logitech",
			controlName: "Left X",
			canonicalName: "left_stick_x",
			event: "axis_0",
		},
		{
			id: "ctrl-logitech-14",
			ownerId: "family-logitech",
			controlName: "Left Y",
			canonicalName: "left_stick_y",
			event: "axis_1",
		},
		{
			id: "ctrl-logitech-15",
			ownerId: "family-logitech",
			controlName: "L3",
			canonicalName: "left_stick_press",
			event: "button_10",
		},
		{
			id: "ctrl-logitech-16",
			ownerId: "family-logitech",
			controlName: "Right X",
			canonicalName: "right_stick_x",
			event: "axis_2",
		},
		{
			id: "ctrl-logitech-17",
			ownerId: "family-logitech",
			controlName: "Right Y",
			canonicalName: "right_stick_y",
			event: "axis_3",
		},
		{
			id: "ctrl-logitech-18",
			ownerId: "family-logitech",
			controlName: "R3",
			canonicalName: "right_stick_press",
			event: "button_11",
		},
		{
			id: "ctrl-logitech-19",
			ownerId: "family-logitech",
			controlName: "Start",
			canonicalName: "start",
			event: "button_9",
		},
		{
			id: "ctrl-logitech-20",
			ownerId: "family-logitech",
			controlName: "Back",
			canonicalName: "back",
			event: "button_8",
		},

		// Microsoft Xbox family controls
		{
			id: "ctrl-xbox-1",
			ownerId: "family-xbox",
			controlName: "A",
			canonicalName: "button_south",
			event: "button_0",
		},
		{
			id: "ctrl-xbox-2",
			ownerId: "family-xbox",
			controlName: "B",
			canonicalName: "button_east",
			event: "button_1",
		},
		{
			id: "ctrl-xbox-3",
			ownerId: "family-xbox",
			controlName: "X",
			canonicalName: "button_west",
			event: "button_2",
		},
		{
			id: "ctrl-xbox-4",
			ownerId: "family-xbox",
			controlName: "Y",
			canonicalName: "button_north",
			event: "button_3",
		},
		{
			id: "ctrl-xbox-5",
			ownerId: "family-xbox",
			controlName: "D-Up",
			canonicalName: "dpad_up",
			event: "button_12",
		},
		{
			id: "ctrl-xbox-6",
			ownerId: "family-xbox",
			controlName: "D-Down",
			canonicalName: "dpad_down",
			event: "button_13",
		},
		{
			id: "ctrl-xbox-7",
			ownerId: "family-xbox",
			controlName: "D-Left",
			canonicalName: "dpad_left",
			event: "button_14",
		},
		{
			id: "ctrl-xbox-8",
			ownerId: "family-xbox",
			controlName: "D-Right",
			canonicalName: "dpad_right",
			event: "button_15",
		},
		{
			id: "ctrl-xbox-9",
			ownerId: "family-xbox",
			controlName: "LB",
			canonicalName: "left_shoulder",
			event: "button_4",
		},
		{
			id: "ctrl-xbox-10",
			ownerId: "family-xbox",
			controlName: "RB",
			canonicalName: "right_shoulder",
			event: "button_5",
		},
		{
			id: "ctrl-xbox-11",
			ownerId: "family-xbox",
			controlName: "LT",
			canonicalName: "left_trigger",
			event: "axis_2",
		},
		{
			id: "ctrl-xbox-12",
			ownerId: "family-xbox",
			controlName: "RT",
			canonicalName: "right_trigger",
			event: "axis_5",
		},
		{
			id: "ctrl-xbox-13",
			ownerId: "family-xbox",
			controlName: "Left X",
			canonicalName: "left_stick_x",
			event: "axis_0",
		},
		{
			id: "ctrl-xbox-14",
			ownerId: "family-xbox",
			controlName: "Left Y",
			canonicalName: "left_stick_y",
			event: "axis_1",
		},
		{
			id: "ctrl-xbox-15",
			ownerId: "family-xbox",
			controlName: "LS",
			canonicalName: "left_stick_press",
			event: "button_9",
		},
		{
			id: "ctrl-xbox-16",
			ownerId: "family-xbox",
			controlName: "Right X",
			canonicalName: "right_stick_x",
			event: "axis_3",
		},
		{
			id: "ctrl-xbox-17",
			ownerId: "family-xbox",
			controlName: "Right Y",
			canonicalName: "right_stick_y",
			event: "axis_4",
		},
		{
			id: "ctrl-xbox-18",
			ownerId: "family-xbox",
			controlName: "RS",
			canonicalName: "right_stick_press",
			event: "button_10",
		},
		{
			id: "ctrl-xbox-19",
			ownerId: "family-xbox",
			controlName: "Start",
			canonicalName: "start",
			event: "button_7",
		},
		{
			id: "ctrl-xbox-20",
			ownerId: "family-xbox",
			controlName: "Back",
			canonicalName: "back",
			event: "button_6",
		},

		// Sony DualShock family controls
		{
			id: "ctrl-ds-1",
			ownerId: "family-dualshock",
			controlName: "Cross",
			canonicalName: "button_south",
			event: "button_0",
		},
		{
			id: "ctrl-ds-2",
			ownerId: "family-dualshock",
			controlName: "Circle",
			canonicalName: "button_east",
			event: "button_1",
		},
		{
			id: "ctrl-ds-3",
			ownerId: "family-dualshock",
			controlName: "Square",
			canonicalName: "button_west",
			event: "button_3",
		},
		{
			id: "ctrl-ds-4",
			ownerId: "family-dualshock",
			controlName: "Triangle",
			canonicalName: "button_north",
			event: "button_2",
		},
		{
			id: "ctrl-ds-5",
			ownerId: "family-dualshock",
			controlName: "Up",
			canonicalName: "dpad_up",
			event: "button_11",
		},
		{
			id: "ctrl-ds-6",
			ownerId: "family-dualshock",
			controlName: "Down",
			canonicalName: "dpad_down",
			event: "button_12",
		},
		{
			id: "ctrl-ds-7",
			ownerId: "family-dualshock",
			controlName: "Left",
			canonicalName: "dpad_left",
			event: "button_13",
		},
		{
			id: "ctrl-ds-8",
			ownerId: "family-dualshock",
			controlName: "Right",
			canonicalName: "dpad_right",
			event: "button_14",
		},
		{
			id: "ctrl-ds-9",
			ownerId: "family-dualshock",
			controlName: "L1",
			canonicalName: "left_shoulder",
			event: "button_4",
		},
		{
			id: "ctrl-ds-10",
			ownerId: "family-dualshock",
			controlName: "R1",
			canonicalName: "right_shoulder",
			event: "button_5",
		},
		{
			id: "ctrl-ds-11",
			ownerId: "family-dualshock",
			controlName: "L2",
			canonicalName: "left_trigger",
			event: "axis_3",
		},
		{
			id: "ctrl-ds-12",
			ownerId: "family-dualshock",
			controlName: "R2",
			canonicalName: "right_trigger",
			event: "axis_4",
		},
		{
			id: "ctrl-ds-13",
			ownerId: "family-dualshock",
			controlName: "Left X",
			canonicalName: "left_stick_x",
			event: "axis_0",
		},
		{
			id: "ctrl-ds-14",
			ownerId: "family-dualshock",
			controlName: "Left Y",
			canonicalName: "left_stick_y",
			event: "axis_1",
		},
		{
			id: "ctrl-ds-15",
			ownerId: "family-dualshock",
			controlName: "L3",
			canonicalName: "left_stick_press",
			event: "button_7",
		},
		{
			id: "ctrl-ds-16",
			ownerId: "family-dualshock",
			controlName: "Right X",
			canonicalName: "right_stick_x",
			event: "axis_2",
		},
		{
			id: "ctrl-ds-17",
			ownerId: "family-dualshock",
			controlName: "Right Y",
			canonicalName: "right_stick_y",
			event: "axis_5",
		},
		{
			id: "ctrl-ds-18",
			ownerId: "family-dualshock",
			controlName: "R3",
			canonicalName: "right_stick_press",
			event: "button_8",
		},
		{
			id: "ctrl-ds-19",
			ownerId: "family-dualshock",
			controlName: "Options",
			canonicalName: "start",
			event: "button_9",
		},
		{
			id: "ctrl-ds-20",
			ownerId: "family-dualshock",
			controlName: "Create",
			canonicalName: "back",
			event: "button_4",
		},

		// Logitech Dual Action controller overrides
		{
			id: "ctrl-lda-1",
			ownerId: "controller-logitech-dual-action",
			controlName: "A",
			canonicalName: "button_south",
			event: "button_1",
		},
		{
			id: "ctrl-lda-2",
			ownerId: "controller-logitech-dual-action",
			controlName: "B",
			canonicalName: "button_east",
			event: "button_2",
		},
	],
};
